language: shell
os: linux
dist: xenial
git:
  depth: false

services:
  - docker

env:
  global:
    - LATEST=38
    - LATEST_LTS=35
  jobs:
    - "DB_TYPE=all VERSION=35 DOCKERFILE=./Dockerfile"
    - "DB_TYPE=mysqli VERSION=35 DOCKERFILE=./Dockerfile"
    - "DB_TYPE=pgsql  VERSION=35 DOCKERFILE=./Dockerfile"
    - "DB_TYPE=all VERSION=38 DOCKERFILE=./Dockerfile"
    - "DB_TYPE=mysqli VERSION=38 DOCKERFILE=./Dockerfile"
    - "DB_TYPE=pgsql  VERSION=38 DOCKERFILE=./Dockerfile"

script: bash ./travis/build.sh

deploy:
  - provider: script
    on:
       branch: master
    script: bash ./travis/deploy.sh
       